### ISSUE TITLE
Some files seems missing?

### ISSUE THREAD

**Issue by llcc343** [phheise/cvt#2]
Hi, I am studying efficient dvo which requires cvt library. When I check the source code, I found edvo requires Linearizer.h in rgbdvo directory. But I found it does not exists in current version of cvt. Have u deleted it ?

**Comment by phheise** [comment]
It could be that we accidentally removed the file. I haven’t used the dvo code for a long time. I will try to add the file as soon as i have some time…

**Comment by llcc343** [comment]
Thanks, I am looking forward to run the edvo for evaluation. And I have a question , the formula to update the affine illumination brightness parameter 'beta' seems wrong. I have use the update formula in my code, it seems that the intensity residual could not converge.

**Comment by llcc343** [comment]
Hi phheise,
     Could you add the missing file please? I want to test edvo , and make comparison witn my algorithm.

**Comment by phheise** [comment]
I added the missing file... I haven't tested if it fixes the issue.
